### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by michaellevy** [ecohealthalliance/yenpathy#1]
Hey, this came in really handy for me, thank you for putting it together! I ran into a few hiccups that I wanted to let you know about if you are interested in aiming for a broader audience.

1. The c++ compiler wasn't specified for installation, so the default worked on one of my machines, but on another I needed `withr::with_envvar(list(PKG_CXXFLAGS="-std=c++11"), devtools::install_github("ecohealthalliance/yenpathy"))`
2. There's a hidden `magrittr` dependency. If I don't have the package attached I get an error about `%<>%` not being found.
3. If there's NA in the edgelist it breaks in C++, which can be hard to debug/spot. Maybe throw an error from R?

I was happily surprised to find that the function works on character edgelists as well as integer. 

Thanks again!

**Comment by toph-allen** [comment]
Hi!

Thanks for your feedback. I'm so glad you found the package useful — this seemed like a big gap in functionality to me. [This series of commits](https://github.com/ecohealthalliance/yenpathy/compare/779e91a..7568385) fixes your issues (2) and (3).

Regarding issue (1): I'm not very familiar with C++ and Rcpp best practices. Are those environment variables the kind of things you usually specify in `src/Makevars`?

**Comment by toph-allen** [comment]
Update: Following instructions in [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b11-code), I added `SystemRequirements: C++11` to `DESCRIPTION`. However, if that doesn't work, it looks like the next step would be to create `src/Makevars` and put `CXX_STD = CXX11` in it. Let me know if that'd solve your issue.
